<<<<<<< HEAD
rules:
  aile:
    court: "Aile Mahkemesi"
    note: "Yetki çoğunlukla taraflardan birinin yerleşim yeri."
  borclar:
    court: "Asliye Hukuk Mahkemesi"
    note: "Genel görevli mahkeme."
=======
rules:
  aile:
    court: "Aile Mahkemesi"
    note: "Yetki çoğunlukla taraflardan birinin yerleşim yeri."
  borclar:
    court: "Asliye Hukuk Mahkemesi"
    note: "Genel görevli mahkeme."
>>>>>>> 4fb0536 (Add LexAi-main files from local deneme123)
