matrix:
  nafaka:
    zorunlu: ["gelir belgesi","gider dökümü"]
    guclendirici: ["kira kontratı","faturalar","sağlık raporu"]
    opsiyonel: ["tanık beyanı"]
    etkiler: {"gelir belgesi": 8, "gider dökümü": 6, "kira kontratı": 4}
  ziynet:
    zorunlu: ["düğün takılarına ilişkin delil","tanık beyanı"]
    guclendirici: ["fotoğraf","video","fiş/fatura"]
    opsiyonel: ["yazışmalar"]
    etkiler: {"tanık beyanı": 7, "fotoğraf": 4}
