<<<<<<< HEAD
dava_turu:
  aile: ["nafaka","boşanma","velayet","ziynet"]
  borclar: ["tazminat","haksız fiil","alacak"]

hak_ihlali_turu:
  nafaka: ["tedbir nafakası","yoksulluk nafakası"]
  ziynet: ["ziynet","altın","takı"]
  tazminat: ["maddi zarar","manevi zarar","tazminat"]

taraf_iliskisi:
  esler: ["eş","karı","koca"]
  isci_isveren: ["işçi","işveren","kıdem","ihbar"]
=======
dava_turu:
  aile: ["nafaka","boşanma","velayet","ziynet"]
  borclar: ["tazminat","haksız fiil","alacak"]

hak_ihlali_turu:
  nafaka: ["tedbir nafakası","yoksulluk nafakası"]
  ziynet: ["ziynet","altın","takı"]
  tazminat: ["maddi zarar","manevi zarar","tazminat"]

taraf_iliskisi:
  esler: ["eş","karı","koca"]
  isci_isveren: ["işçi","işveren","kıdem","ihbar"]
>>>>>>> 4fb0536 (Add LexAi-main files from local deneme123)
